/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as TableOverviewImport } from "./routes/tableOverview";
import { Route as CandleSticksImport } from "./routes/candleSticks";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const TableOverviewRoute = TableOverviewImport.update({
  id: "/tableOverview",
  path: "/tableOverview",
  getParentRoute: () => rootRoute,
} as any);

const CandleSticksRoute = CandleSticksImport.update({
  id: "/candleSticks",
  path: "/candleSticks",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/candleSticks": {
      id: "/candleSticks";
      path: "/candleSticks";
      fullPath: "/candleSticks";
      preLoaderRoute: typeof CandleSticksImport;
      parentRoute: typeof rootRoute;
    };
    "/tableOverview": {
      id: "/tableOverview";
      path: "/tableOverview";
      fullPath: "/tableOverview";
      preLoaderRoute: typeof TableOverviewImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/candleSticks": typeof CandleSticksRoute;
  "/tableOverview": typeof TableOverviewRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/candleSticks": typeof CandleSticksRoute;
  "/tableOverview": typeof TableOverviewRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/candleSticks": typeof CandleSticksRoute;
  "/tableOverview": typeof TableOverviewRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/candleSticks" | "/tableOverview";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/candleSticks" | "/tableOverview";
  id: "__root__" | "/" | "/candleSticks" | "/tableOverview";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CandleSticksRoute: typeof CandleSticksRoute;
  TableOverviewRoute: typeof TableOverviewRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandleSticksRoute: CandleSticksRoute,
  TableOverviewRoute: TableOverviewRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/candleSticks",
        "/tableOverview"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/candleSticks": {
      "filePath": "candleSticks.tsx"
    },
    "/tableOverview": {
      "filePath": "tableOverview.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
